[package]
name = "servicekit"
version = "0.1.0"
edition = "2024"
publish = false

[lib]
name = "servicekit"
path = "src/lib.rs"
bench = false

[features]
default = []

[dependencies]
naos-sys = { path = "../naos-sys" }
naos-idl = { path = "../naos-idl", features = ["alloc"] }
log = { version = "0.4.34", default-features = false }

[target.'cfg(target_os = "linux")'.dependencies]
libc = "0.2"
naos-ipc-core-sys = { path = "../naos-ipc-core-sys" }
tokio = { version = "1.47", default-features = false, features = [
    "io-util",
    "macros",
    "net",
    "rt",
    "rt-multi-thread",
    "sync",
    "time",
] }

[target.'cfg(target_os = "naos")'.dependencies]
naos-runtime = { path = "../naos-runtime", features = ["alloc", "entry"] }
tokio = { version = "1.47", default-features = false, features = [
    "macros",
    "rt",
    "rt-multi-thread",
    "sync",
    "time",
] }
